### PR TITLE
Dashboard Img Placeholder

### LINKED ISSUE #6: The dashboard should have a placeholder for images too.
We should have the images for the clubs on the dashboard, either in the foreground or in the background behind the text. The first thing we should do to implement this is to put in a placeholder.

### PR DESCRIPTION
**Pull request by russell-leung**
Also fixed a couple small things and added NavBar component to the default layout

### CODE REVIEW

**Comment by Sabramz** [comment]
W

**Review by Sabramz — APPROVED** [review]
W, but we should be using layout.tsx at root to create a default layout for all pages that are below root.

**Comment by russell-leung** [comment]
isn't _app.tsx react/next version of layout.tsx

**Comment by Sabramz** [comment]
Yeah I'm dum

**Pull request merged**
